# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  #  cphboxback-app:
  #    image: cphboxback
  #    environment:
  #      - _JAVA_OPTIONS=-Xmx512m -Xms256m
  #      - SPRING_PROFIL
  #      - ES_ACTIVE=prod,api-docs
  #      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
  #      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
  #      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
  #      - SPRING_DATA_MONGODB_URI=mongodb://cphboxback-mongodb:27017
  #      - SPRING_DATA_MONGODB_DATABASE=cphBoxBack
  #      - JHIPSTER_CACHE_REDIS_SERVER=redis://cphboxback-redis:6379
  #      - JHIPSTER_CACHE_REDIS_CLUSTER=false
  #      # - JHIPSTER_CACHE_REDIS_SERVER=redis://cphboxback-redis:6379
  #      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
  #      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  #    # If you want to expose these ports outside your dev PC,
  #    # remove the "127.0.0.1:" prefix
  #    ports:
  #      - 127.0.0.1:8080:8080
  cphboxback-mongodb:
    image: mongo:4.4.15
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27017:27017
    # volumes:
    #   - ~/volumes/jhipster/cphBoxBack/mongodb/:/data/db/
  cphboxback-redis:
    image: redis:6.2.7
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6379:6379

  jhipster-registry:
    image: jhipster/jhipster-registry:v7.3.0
    volumes:
      - ./central-server-config:/central-config
    # When run with the "dev" Spring profile, the JHipster Registry will
    # read the config from the local filesystem (central-server-config directory)
    # When run with the "prod" Spring profile, it will read the configuration from a Git repository
    # See https://www.jhipster.tech/jhipster-registry/#spring-cloud-config
    environment:
      - JHIPSTER_SLEEP=20
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8761:8761
