# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjMwNDlmZThlMGRiOTllYjc5NzgxNTdjYzI4MTNlNzZmOTNhMzk2Zjc2ZmE5NDhmNTY0ODRmOWM0NDgyZjBjNDNkNDk0NTA0MTlkMTk5ZWJiYzFlYmZlMGU2ZGJmMzE4ODc2NTNkNzhmNWJkNmNhZDhiZWM2MzdjNmNhNDRmM2M=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
